In [1]:
import pandas as pd
from sodapy import Socrata

# Get my LA City App Token from the api_keys module file
from api_keys import lacity_app_token

In [2]:
# Reference: https://data.lacity.org/Public-Safety/Crime-Data-from-2020-to-Present/2nrs-mtv8/about_data
client = Socrata("data.lacity.org", lacity_app_token)

# Approx: 7-8 Minutes
results = client.get_all("2nrs-mtv8")

# Convert to pandas DataFrame
crime_df = pd.DataFrame.from_records(results)

crime_df

,dr_no,date_rptd,date_occ,time_occ,area,area_name,rpt_dist_no,part_1_2,crm_cd,crm_cd_desc,...,status,status_desc,crm_cd_1,location,lat,lon,crm_cd_2,cross_street,crm_cd_3,crm_cd_4
0,010304468,2020-01-08T00:00:00.000,2020-01-08T00:00:00.000,2230,03,Southwest,0377,2,624,BATTERY - SIMPLE ASSAULT,...,AO,Adult Other,624,1100 W 39TH PL,34.0141,-118.2978,NaN,NaN,NaN,NaN
1,190101086,2020-01-02T00:00:00.000,2020-01-01T00:00:00.000,0330,01,Central,0163,2,624,BATTERY - SIMPLE ASSAULT,...,IC,Invest Cont,624,700 S HILL ST,34.0459,-118.2545,NaN,NaN,NaN,NaN
2,200110444,2020-04-14T00:00:00.000,2020-02-13T00:00:00.000,1200,01,Central,0155,2,845,SEX OFFENDER REGISTRANT OUT OF COMPLIANCE,...,AA,Adult Arrest,845,200 E 6TH ST,34.0448,-118.2474,NaN,NaN,NaN,NaN
3,191501505,2020-01-01T00:00:00.000,2020-01-01T00:00:00.000,1730,15,N Hollywood,1543,2,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),...,IC,Invest Cont,745,5400 CORTEEN PL,34.1685,-118.4019,998,NaN,NaN,NaN
4,191921269,2020-01-01T00:00:00.000,2020-01-01T00:00:00.000,0415,19,Mission,1998,2,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",...,IC,Invest Cont,740,14400 TITUS ST,34.2198,-118.4468,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
857653,231606525,2023-03-22T00:00:00.000,2023-03-22T00:00:00.000,1000,16,Foothill,1602,1,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",...,IC,Invest Cont,230,12800 FILMORE ST,34.279,-118.4116,NaN,NaN,NaN,NaN
857654,231210064,2023-04-12T00:00:00.000,2023-04-12T00:00:00.000,1630,12,77th Street,1239,1,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",...,IC,Invest Cont,230,6100 S VERMONT AV,33.9841,-118.2915,NaN,NaN,NaN,NaN
857655,230115220,2023-07-02T00:00:00.000,2023-07-01T00:00:00.000,0001,01,Central,0154,1,352,PICKPOCKET,...,IC,Invest Cont,352,500 S MAIN ST,34.0467,-118.2485,NaN,NaN,NaN,NaN
857656,230906458,2023-03-05T00:00:00.000,2023-03-05T00:00:00.000,0900,09,Van Nuys,0914,2,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),...,IC,Invest Cont,745,14500 HARTLAND ST,34.1951,-118.4487,NaN,NaN,NaN,NaN
857657,230319786,2023-11-10T00:00:00.000,2023-11-09T00:00:00.000,2300,03,Southwest,0395,1,331,THEFT FROM MOTOR VEHICLE - GRAND ($950.01 AND ...,...,IC,Invest Cont,331,4100 S HOBART BL,34.0091,-118.3078,NaN,NaN,NaN,NaN

In [41]:
final_crime_df = crime_df.copy()

final_crime_df

,dr_no,date_rptd,date_occ,time_occ,area,area_name,rpt_dist_no,part_1_2,crm_cd,crm_cd_desc,...,status,status_desc,crm_cd_1,location,lat,lon,crm_cd_2,cross_street,crm_cd_3,crm_cd_4
0,010304468,2020-01-08T00:00:00.000,2020-01-08T00:00:00.000,2230,03,Southwest,0377,2,624,BATTERY - SIMPLE ASSAULT,...,AO,Adult Other,624,1100 W 39TH PL,34.0141,-118.2978,NaN,NaN,NaN,NaN
1,190101086,2020-01-02T00:00:00.000,2020-01-01T00:00:00.000,0330,01,Central,0163,2,624,BATTERY - SIMPLE ASSAULT,...,IC,Invest Cont,624,700 S HILL ST,34.0459,-118.2545,NaN,NaN,NaN,NaN
2,200110444,2020-04-14T00:00:00.000,2020-02-13T00:00:00.000,1200,01,Central,0155,2,845,SEX OFFENDER REGISTRANT OUT OF COMPLIANCE,...,AA,Adult Arrest,845,200 E 6TH ST,34.0448,-118.2474,NaN,NaN,NaN,NaN
3,191501505,2020-01-01T00:00:00.000,2020-01-01T00:00:00.000,1730,15,N Hollywood,1543,2,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),...,IC,Invest Cont,745,5400 CORTEEN PL,34.1685,-118.4019,998,NaN,NaN,NaN
4,191921269,2020-01-01T00:00:00.000,2020-01-01T00:00:00.000,0415,19,Mission,1998,2,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",...,IC,Invest Cont,740,14400 TITUS ST,34.2198,-118.4468,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
857653,231606525,2023-03-22T00:00:00.000,2023-03-22T00:00:00.000,1000,16,Foothill,1602,1,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",...,IC,Invest Cont,230,12800 FILMORE ST,34.279,-118.4116,NaN,NaN,NaN,NaN
857654,231210064,2023-04-12T00:00:00.000,2023-04-12T00:00:00.000,1630,12,77th Street,1239,1,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",...,IC,Invest Cont,230,6100 S VERMONT AV,33.9841,-118.2915,NaN,NaN,NaN,NaN
857655,230115220,2023-07-02T00:00:00.000,2023-07-01T00:00:00.000,0001,01,Central,0154,1,352,PICKPOCKET,...,IC,Invest Cont,352,500 S MAIN ST,34.0467,-118.2485,NaN,NaN,NaN,NaN
857656,230906458,2023-03-05T00:00:00.000,2023-03-05T00:00:00.000,0900,09,Van Nuys,0914,2,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),...,IC,Invest Cont,745,14500 HARTLAND ST,34.1951,-118.4487,NaN,NaN,NaN,NaN
857657,230319786,2023-11-10T00:00:00.000,2023-11-09T00:00:00.000,2300,03,Southwest,0395,1,331,THEFT FROM MOTOR VEHICLE - GRAND ($950.01 AND ...,...,IC,Invest Cont,331,4100 S HOBART BL,34.0091,-118.3078,NaN,NaN,NaN,NaN

In [42]:
final_crime_df["date_rptd"] = final_crime_df["date_rptd"].str.split('T').str[0]
final_crime_df["date_occ"] = final_crime_df["date_occ"].str.split('T').str[0]

final_crime_df["date_rptd"] = pd.to_datetime(final_crime_df["date_rptd"]).dt.date
final_crime_df["date_occ"] = pd.to_datetime(final_crime_df["date_occ"]).dt.date

final_crime_df.head()

,dr_no,date_rptd,date_occ,time_occ,area,area_name,rpt_dist_no,part_1_2,crm_cd,crm_cd_desc,...,status,status_desc,crm_cd_1,location,lat,lon,crm_cd_2,cross_street,crm_cd_3,crm_cd_4
0,010304468,2020-01-08,2020-01-08,2230,03,Southwest,0377,2,624,BATTERY - SIMPLE ASSAULT,...,AO,Adult Other,624,1100 W 39TH PL,34.0141,-118.2978,NaN,NaN,NaN,NaN
1,190101086,2020-01-02,2020-01-01,0330,01,Central,0163,2,624,BATTERY - SIMPLE ASSAULT,...,IC,Invest Cont,624,700 S HILL ST,34.0459,-118.2545,NaN,NaN,NaN,NaN
2,200110444,2020-04-14,2020-02-13,1200,01,Central,0155,2,845,SEX OFFENDER REGISTRANT OUT OF COMPLIANCE,...,AA,Adult Arrest,845,200 E 6TH ST,34.0448,-118.2474,NaN,NaN,NaN,NaN
3,191501505,2020-01-01,2020-01-01,1730,15,N Hollywood,1543,2,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),...,IC,Invest Cont,745,5400 CORTEEN PL,34.1685,-118.4019,998,NaN,NaN,NaN
4,191921269,2020-01-01,2020-01-01,0415,19,Mission,1998,2,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",...,IC,Invest Cont,740,14400 TITUS ST,34.2198,-118.4468,NaN,NaN,NaN,NaN

In [43]:
unique_crimes = final_crime_df["crm_cd_desc"].unique()

print("Unique Crimes:")
print()

for crime in unique_crimes:
    print(crime)

Unique Crimes:

BATTERY - SIMPLE ASSAULT
SEX OFFENDER REGISTRANT OUT OF COMPLIANCE
VANDALISM - MISDEAMEANOR ($399 OR UNDER)
VANDALISM - FELONY ($400 & OVER, ALL CHURCH VANDALISMS)
RAPE, FORCIBLE
SHOPLIFTING - PETTY THEFT ($950 & UNDER)
OTHER MISCELLANEOUS CRIME
THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LIVESTK,PROD
BURGLARY FROM VEHICLE
CRIMINAL THREATS - NO WEAPON DISPLAYED
ARSON
INTIMATE PARTNER - SIMPLE ASSAULT
THEFT PLAIN - PETTY ($950 & UNDER)
THEFT OF IDENTITY
ROBBERY
ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT
BURGLARY
VEHICLE - STOLEN
THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER)
BRANDISH WEAPON
INTIMATE PARTNER - AGGRAVATED ASSAULT
BUNCO, GRAND THEFT
THEFT, PERSON
BATTERY WITH SEXUAL CONTACT
BIKE - STOLEN
BATTERY POLICE (SIMPLE)
LETTERS, LEWD  -  TELEPHONE CALLS, LEWD
VIOLATION OF COURT ORDER
TRESPASSING
THEFT FROM MOTOR VEHICLE - GRAND ($950.01 AND OVER)
VIOLATION OF RESTRAINING ORDER
DISTURBING THE PEACE
THEFT FROM MOTOR VEHICLE - ATTEMPT
THROWING OBJECT AT MOVING VEHICLE
EXTORTION
SEX,UNLAWFUL(INC MUTUAL CONSENT, PENETRATION W/ FRGN OBJ
CHILD STEALING
CRM AGNST CHLD (13 OR UNDER) (14-15 & SUSP 10 YRS OLDER)
ATTEMPTED ROBBERY
OTHER ASSAULT
BOMB SCARE
DOCUMENT FORGERY / STOLEN FELONY
SEXUAL PENETRATION W/FOREIGN OBJECT
SHOTS FIRED AT INHABITED DWELLING
BURGLARY, ATTEMPTED
INDECENT EXPOSURE
ORAL COPULATION
EMBEZZLEMENT, GRAND THEFT ($950.01 & OVER)
VIOLATION OF TEMPORARY RESTRAINING ORDER
BUNCO, PETTY THEFT
KIDNAPPING - GRAND ATTEMPT
SHOPLIFTING-GRAND THEFT ($950.01 & OVER)
RESISTING ARREST
DISCHARGE FIREARMS/SHOTS FIRED
THREATENING PHONE CALLS/LETTERS
KIDNAPPING
LEWD/LASCIVIOUS ACTS WITH CHILD
LEWD CONDUCT
UNAUTHORIZED COMPUTER ACCESS
PURSE SNATCHING
SODOMY/SEXUAL CONTACT B/W PENIS OF ONE PERS TO ANUS OTH
CHILD NEGLECT (SEE 300 W.I.C.)
CONTEMPT OF COURT
CHILD ANNOYING (17YRS & UNDER)
BUNCO, ATTEMPT
CHILD ABUSE (PHYSICAL) - SIMPLE ASSAULT
PIMPING
STALKING
THEFT PLAIN - ATTEMPT
RAPE, ATTEMPTED
SHOPLIFTING - ATTEMPT
THEFT FROM PERSON - ATTEMPT
FALSE IMPRISONMENT
BURGLARY FROM VEHICLE, ATTEMPTED
FAILURE TO YIELD
VEHICLE - ATTEMPT STOLEN
EMBEZZLEMENT, PETTY THEFT ($950 & UNDER)
DEFRAUDING INNKEEPER/THEFT OF SERVICES, $950 & UNDER
COUNTERFEIT
CREDIT CARDS, FRAUD USE ($950 & UNDER
PICKPOCKET
SHOTS FIRED AT MOVING VEHICLE, TRAIN OR AIRCRAFT
CRIMINAL HOMICIDE
PROWLER
DOCUMENT WORTHLESS ($200 & UNDER)
DEFRAUDING INNKEEPER/THEFT OF SERVICES, OVER $950.01
ASSAULT WITH DEADLY WEAPON ON POLICE OFFICER
DISHONEST EMPLOYEE - GRAND THEFT
HUMAN TRAFFICKING - COMMERCIAL SEX ACTS
CHILD PORNOGRAPHY
PEEPING TOM
BATTERY ON A FIREFIGHTER
TILL TAP - PETTY ($950 & UNDER)
CHILD ABUSE (PHYSICAL) - AGGRAVATED ASSAULT
TILL TAP - GRAND THEFT ($950.01 & OVER)
HUMAN TRAFFICKING - INVOLUNTARY SERVITUDE
FIREARMS RESTRAINING ORDER (FIREARMS RO)
DRIVING WITHOUT OWNER CONSENT (DWOC)
DOCUMENT WORTHLESS ($200.01 & OVER)
CRUELTY TO ANIMALS
CREDIT CARDS, FRAUD USE ($950.01 & OVER)
LYNCHING - ATTEMPTED
PANDERING
ILLEGAL DUMPING
RECKLESS DRIVING
VEHICLE, STOLEN - OTHER (MOTORIZED SCOOTERS, BIKES, ETC)
PETTY THEFT - AUTO REPAIR
MANSLAUGHTER, NEGLIGENT
FALSE POLICE REPORT
PURSE SNATCHING - ATTEMPT
BIKE - ATTEMPTED STOLEN
CONSPIRACY
CONTRIBUTING
WEAPONS POSSESSION/BOMBING
BRIBERY
BOAT - STOLEN
GRAND THEFT / INSURANCE FRAUD
DISRUPT SCHOOL
DISHONEST EMPLOYEE - PETTY THEFT
THEFT, COIN MACHINE - ATTEMPT
THEFT, COIN MACHINE - PETTY ($950 & UNDER)
LYNCHING
REPLICA FIREARMS(SALE,DISPLAY,MANUFACTURE OR DISTRIBUTE)
DRUGS, TO A MINOR
GRAND THEFT / AUTO REPAIR
THEFT, COIN MACHINE - GRAND ($950.01 & OVER)
DRUNK ROLL
CHILD ABANDONMENT
TELEPHONE PROPERTY - DAMAGE
PICKPOCKET, ATTEMPT
BEASTIALITY, CRIME AGAINST NATURE SEXUAL ASSLT WITH ANIM
BIGAMY
FAILURE TO DISPERSE
FIREARMS EMERGENCY PROTECTIVE ORDER (FIREARMS EPO)
INCEST (SEXUAL ACTS BETWEEN BLOOD RELATIVES)
BLOCKING DOOR INDUCTION CENTER
INCITING A RIOT
DISHONEST EMPLOYEE ATTEMPTED THEFT

In [44]:
# UCR Reporting Crime Codes
# Reference: "UCR-COMPSTAT062618.pdf"

final_crime_df["crm_cd"] = final_crime_df["crm_cd"].astype(int)

# Homicide
homicide_codes = [110, 113]

# Rape
rape_codes = [121, 122, 815, 820, 821]

# Robbery
robbery_codes = [210, 220]

# Aggravated Assault
agg_assault_codes = [230, 231, 235]

# Domestic Violence
domestic_violence_codes = [236, 250, 251, 761, 926,
                           626, 627, 647, 763, 928, 930]

# Simple Assault
simple_assault_codes = [435, 436, 437, 622, 623, 624, 625]

# Burglary
burglary_codes = [310, 320]

# Grand Theft Auto (Motor Vehicle Theft)
gta_codes = [510, 520, 433]

# Burglary or Theft from Vehicle
btfv_codes = [330, 331, 410, 420, 421]

# Personal Theft
personal_theft_codes = [350, 351, 352, 353, 450, 451, 452, 453]

# Other Theft
other_theft_codes = [341, 343, 345, 440, 441, 442, 443, 444, 445,
                     470, 471, 472, 473, 474, 475, 480, 485, 487, 491]

ucr_dict = {"Homicide": homicide_codes,
            "Rape": rape_codes,
            "Robbery": robbery_codes,
            "Aggravated Assault": agg_assault_codes,
            "Domestic Violence": domestic_violence_codes,
            "Simple Assault": simple_assault_codes,
            "Burglary": burglary_codes,
            "Grand Theft Auto": gta_codes,
            "Burglary or Theft from Vehicle": btfv_codes,
            "Personal Theft": personal_theft_codes,
            "Other Theft": other_theft_codes}

# Custom map function to insert the crime category for each datapoint in the "crime_category" column based on 'crm_cd'
# Reference: https://favtutor.com/blogs/pandas-map#:~:text=The%20map%20function%20is%20one,DataFrame%20with%20the%20modified%20values.
def map_crime_categories(code):
    # For every crime key and its corresponding list of code values...
    # If code from current crime_df row is in the list of codes from current crime key...
    # Append the "crime_category" column for current row with current crime key
    # Otherwise, Append the "crime_category" column for current row with "Other"
    for crime, codes in ucr_dict.items():
        if code in codes:
            return crime
    return "Other"


final_crime_df["crime_category"] = final_crime_df["crm_cd"].map(map_crime_categories)

final_crime_df.head()

,dr_no,date_rptd,date_occ,time_occ,area,area_name,rpt_dist_no,part_1_2,crm_cd,crm_cd_desc,...,status_desc,crm_cd_1,location,lat,lon,crm_cd_2,cross_street,crm_cd_3,crm_cd_4,crime_category
0,010304468,2020-01-08,2020-01-08,2230,03,Southwest,0377,2,624,BATTERY - SIMPLE ASSAULT,...,Adult Other,624,1100 W 39TH PL,34.0141,-118.2978,NaN,NaN,NaN,NaN,Simple Assault
1,190101086,2020-01-02,2020-01-01,0330,01,Central,0163,2,624,BATTERY - SIMPLE ASSAULT,...,Invest Cont,624,700 S HILL ST,34.0459,-118.2545,NaN,NaN,NaN,NaN,Simple Assault
2,200110444,2020-04-14,2020-02-13,1200,01,Central,0155,2,845,SEX OFFENDER REGISTRANT OUT OF COMPLIANCE,...,Adult Arrest,845,200 E 6TH ST,34.0448,-118.2474,NaN,NaN,NaN,NaN,Other
3,191501505,2020-01-01,2020-01-01,1730,15,N Hollywood,1543,2,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),...,Invest Cont,745,5400 CORTEEN PL,34.1685,-118.4019,998,NaN,NaN,NaN,Other
4,191921269,2020-01-01,2020-01-01,0415,19,Mission,1998,2,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",...,Invest Cont,740,14400 TITUS ST,34.2198,-118.4468,NaN,NaN,NaN,NaN,Other

In [45]:
unique_crime_categories = final_crime_df["crime_category"].unique()

print("Unique Crime Categories:")
print()

for crime_category in unique_crime_categories:
    print(crime_category)

Unique Crime Categories:

Simple Assault
Other
Rape
Other Theft
Burglary or Theft from Vehicle
Domestic Violence
Robbery
Aggravated Assault
Burglary
Grand Theft Auto
Personal Theft
Homicide

In [46]:
keep_columns = ["dr_no",
                "date_rptd",
                "date_occ",
                "time_occ",
                "area_name",
                "crime_category",
                "crm_cd",
                "crm_cd_desc",
                "vict_age",
                "vict_sex",
                "vict_descent",
                "premis_desc",
                "location",
                "cross_street",
                "lat",
                "lon"]

final_crime_df = final_crime_df[keep_columns]

final_crime_df

,dr_no,date_rptd,date_occ,time_occ,area_name,crime_category,crm_cd,crm_cd_desc,vict_age,vict_sex,vict_descent,premis_desc,location,cross_street,lat,lon
0,010304468,2020-01-08,2020-01-08,2230,Southwest,Simple Assault,624,BATTERY - SIMPLE ASSAULT,36,F,B,SINGLE FAMILY DWELLING,1100 W 39TH PL,NaN,34.0141,-118.2978
1,190101086,2020-01-02,2020-01-01,0330,Central,Simple Assault,624,BATTERY - SIMPLE ASSAULT,25,M,H,SIDEWALK,700 S HILL ST,NaN,34.0459,-118.2545
2,200110444,2020-04-14,2020-02-13,1200,Central,Other,845,SEX OFFENDER REGISTRANT OUT OF COMPLIANCE,0,X,X,POLICE FACILITY,200 E 6TH ST,NaN,34.0448,-118.2474
3,191501505,2020-01-01,2020-01-01,1730,N Hollywood,Other,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),76,F,W,"MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)",5400 CORTEEN PL,NaN,34.1685,-118.4019
4,191921269,2020-01-01,2020-01-01,0415,Mission,Other,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",31,X,X,BEAUTY SUPPLY STORE,14400 TITUS ST,NaN,34.2198,-118.4468
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
857653,231606525,2023-03-22,2023-03-22,1000,Foothill,Aggravated Assault,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",25,F,H,SIDEWALK,12800 FILMORE ST,NaN,34.279,-118.4116
857654,231210064,2023-04-12,2023-04-12,1630,77th Street,Aggravated Assault,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",29,M,B,LAUNDROMAT,6100 S VERMONT AV,NaN,33.9841,-118.2915
857655,230115220,2023-07-02,2023-07-01,0001,Central,Personal Theft,352,PICKPOCKET,24,F,H,NIGHT CLUB (OPEN EVENINGS ONLY),500 S MAIN ST,NaN,34.0467,-118.2485
857656,230906458,2023-03-05,2023-03-05,0900,Van Nuys,Other,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),53,F,H,"MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)",14500 HARTLAND ST,NaN,34.1951,-118.4487
857657,230319786,2023-11-10,2023-11-09,2300,Southwest,Burglary or Theft from Vehicle,331,THEFT FROM MOTOR VEHICLE - GRAND ($950.01 AND ...,38,M,W,SINGLE FAMILY DWELLING,4100 S HOBART BL,NaN,34.0091,-118.3078

In [47]:
print(final_crime_df.dtypes)

dr_no             object
date_rptd         object
date_occ          object
time_occ          object
area_name         object
crime_category    object
crm_cd             int32
crm_cd_desc       object
vict_age          object
vict_sex          object
vict_descent      object
premis_desc       object
location          object
cross_street      object
lat               object
lon               object
dtype: object

In [48]:
unique_count_ccats = final_crime_df['crime_category'].nunique()
unique_ccats = final_crime_df['crime_category'].unique()

print(unique_count_ccats)
print()
print(unique_ccats)

12

['Simple Assault' 'Other' 'Rape' 'Other Theft'
 'Burglary or Theft from Vehicle' 'Domestic Violence' 'Robbery'
 'Aggravated Assault' 'Burglary' 'Grand Theft Auto' 'Personal Theft'
 'Homicide']

In [49]:
value_counts = final_crime_df["vict_sex"].value_counts()

value_counts

vict_sex
M    352746
F    314932
X     75775
H        94
-         1
Name: count, dtype: int64

In [51]:
import numpy as np

# Sex Code to Actual:
# M - Male
# F - Female
# X - Unknown
replace_sex_code = {"M": "Male",   
                    "F": "Female",
                    "X": "Unknown",
                    "-": None}

final_crime_df = final_crime_df[~final_crime_df["vict_sex"].isin(["H"])]
final_crime_df["vict_sex"] = final_crime_df["vict_sex"].replace({np.nan: None})
final_crime_df["vict_sex"] = final_crime_df["vict_sex"].replace(replace_sex_code)


    
unique_victim_sex = final_crime_df["vict_sex"].unique()    

print("Unique Victim Sex:")
print()
print(unique_victim_sex)

Unique Victim Sex:

['Female' 'Male' 'Unknown' None]

C:\Users\wazithepa\AppData\Local\Temp\ipykernel_960\922381700.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_crime_df["vict_sex"] = final_crime_df["vict_sex"].replace({np.nan: None})
C:\Users\wazithepa\AppData\Local\Temp\ipykernel_960\922381700.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_crime_df["vict_sex"] = final_crime_df["vict_sex"].replace(replace_sex_code)

In [52]:
# Descent Code to Actual:
# A - Other Asian
# B - Black
# C - Chinese
# D - Cambodian
# F - Filipino
# G - Guamanian
# H - Hispanic/Latin/Mexican
# I - American Indian/Alaskan Native
# J - Japanese
# K - Korean
# L - Laotian
# O - Other
# P - Pacific Islander
# S - Samoan
# U - Hawaiian
# V - Vietnamese
# W - White
# X - Unknown
# Z - Asian Indian
replace_descent_code = {"A": "Other Asian",
                        "B": "Black",
                        "C": "Chinese",
                        "D": "Cambodian",
                        "F": "Filipino",
                        "G": "Guamanian",
                        "H": "Hispanic/Latin/Mexican",
                        "I": "American Indian/Alaskan Native",
                        "J": "Japanese",
                        "K": "Korean",
                        "L": "Laotian",
                        "O": "Other",
                        "P": "Pacific Islander",
                        "S": "Samoan",
                        "U": "Hawaiian",
                        "V": "Vietnamese",
                        "W": "White",
                        "X": "Unknown",
                        "Z": "Asian Indian",
                        "-": None}


final_crime_df["vict_descent"] = final_crime_df["vict_descent"].replace(replace_descent_code)
final_crime_df["vict_descent"] = final_crime_df["vict_descent"].replace({np.nan: None})


unique_victim_descents = final_crime_df["vict_descent"].unique()    

print("Unique Victim Descents:")
print()
print(unique_victim_descents)

Unique Victim Descents:

['Black' 'Hispanic/Latin/Mexican' 'Unknown' 'White' 'Other Asian' 'Other'
 None 'Chinese' 'Filipino' 'Korean' 'American Indian/Alaskan Native'
 'Vietnamese' 'Asian Indian' 'Japanese' 'Pacific Islander' 'Guamanian'
 'Hawaiian' 'Cambodian' 'Laotian' 'Samoan']

C:\Users\wazithepa\AppData\Local\Temp\ipykernel_960\490799442.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_crime_df["vict_descent"] = final_crime_df["vict_descent"].replace(replace_descent_code)
C:\Users\wazithepa\AppData\Local\Temp\ipykernel_960\490799442.py:44: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_crime_df["vict_descent"] = final_crime_df["vict_descent"].replace({np.nan: None})

In [53]:
unique_area_names = final_crime_df["area_name"].unique()

for area in unique_area_names:
    print(area)

Southwest
Central
N Hollywood
Mission
Devonshire
Northeast
Harbor
Van Nuys
West Valley
West LA
Wilshire
Pacific
Rampart
77th Street
Hollenbeck
Southeast
Hollywood
Newton
Topanga
Foothill
Olympic

In [54]:
# Export crime data to CSV
final_crime_df.to_csv("full_crime_data.csv", index = True)